# Every field in a theme file is optional.

# First come some various options
shadow = false  # Don't draw shadows around stacked views
borders = "outset"  # Alternatives are "none" and "outset"

# Here we define the color palette.
[colors]
    background = "93a1a1"
    # If the value is an array, the first valid color will be used.
    # If the terminal doesn't support custom color,
    # non-base colors will be skipped.
    shadow     = ["#93a1a1", "black"]
    view       = "#002b36"

    # Array and simple values have the same effect.
    primary   = ["#93a1a1"]
    secondary = "#839496"
    tertiary  = "#657b83"

    # Hex values can use lower or uppercase.
    # (base color MUST be lowercase)
    title_primary   = "#268bd2"
    title_secondary = "#2aa198"

    # Lower precision values can use only 3 digits.
    highlight          = "#859900"
    highlight_inactive = "#b58900"